#
# This Makefile has been added for convenience: Delete all object and executable files 
# in this directory and its subdirectories by issuing command "make clean".
#
all:
	make -C C/Makefile all
	make -C tests/Makefile all

clean:
	make -C C/Makefile clean
	make -C tests/Makefile clean

