#
# This Makefile has been added for convenience: Delete all object and executable files 
# in this directory and its subdirectories by issuing command "make clean".
#
all:
	make -C C all
	make -C tests all

clean:
	make -C C clean
	make -C tests clean

